apiVersion: v1alpha1
kind: StressTest
notify: true
spec:
  selector:
    name: httpbin.org
  numRequests: 100
  numConcurrent: 10
  restDuration: 1500 # restDuration will always be mentioned in ms
  serverType: "http"
  serverPort: 80
  tests:
    - id: 1
      name: "my test 1"
      type: "GET"
      endpoint: "/delay/5?foo=bar&bar=baz"
      validResponseCodes:
        - 200
        - 201

    - id: 2
      name: "my test 2"
      type: "POST"
      endpoint: "/post"
      validResponseCodes:
        - 200
        - 201
      # the body must always be encoding in base64
      # Linux command echo '<your-text>' | base64
      body: "eyJpZCI6MSwidW5pcXVlSWQiOjExLCJmaXJzdE5hbWUiOiJKYXdhaGFyIiwibGFzdE5hbWUiOiJTaXZhIiwidXNlck5hbWUiOiJzcHJpbnR0MDEiLCJlbWFpbCI6ImpzaXZhQGF2aWdvc29sdXRpb25zLmNvbSIsInBhc3N3b3JkIjoiYXBwMTAwIiwiZW5hYmxlZCI6dHJ1ZX0="
      headers:
        Content-Type: "application/json"
        X-Requested-With: "XMLHttpRequest"
      auth:
        Bearer: "dGhpcyBpcyBhIHRva2VuCg=="
  executionOrder:
    - 1
    - 2
