apiVersion: v1alpha1
kind: StressTest
notify: true
spec:
  selector:
    name: httpbin.org
  numRequests: 200
  numConcurrent: 10
  restDuration: 1500 # restDuration will always be mentioned in ms
  serverType: "http"
  serverPort: 80
  tests:
    - id: 1
      name: "My Test 1"
      type: "GET"
      endpoint: "/delay/1?foo=bar&bar=baz"
      validResponseCodes:
        - 200
        - 201

    - id: 2
      name: "My Test 2"
      type: "POST"
      endpoint: "/post"
      validResponseCodes:
        - 200
        - 201
      # the body must always be encoding in base64
      # Linux command echo '<your-text>' | base64
      body: "eyJpZCI6MSwidW5pcXVlSWQiOjExLCJmaXJzdE5hbWUiOiJKYXdhaGFyIiwibGFzdE5hbWUiOiJTaXZhIiwidXNlck5hbWUiOiJzcHJpbnR0MDEiLCJlbWFpbCI6ImpzaXZhQGF2aWdvc29sdXRpb25zLmNvbSIsInBhc3N3b3JkIjoiYXBwMTAwIiwiZW5hYmxlZCI6dHJ1ZX0="
      headers:
        Content-Type: "application/json"
        X-Requested-With: "XMLHttpRequest"
      auth:
        Bearer: "dGhpcyBpcyBhIHRva2VuCg=="
    - id: 3
      name: "My Test 3"
      type: "GET"
      endpoint: "/image/png"
      validResponseCodes:
        - 200
        - 201
  executionOrder:
    - 1
    - 3
    - 2
