apiVersion: v1
data:
  in-cluster: "true"
  docker-env: "true"
kind: ConfigMap
metadata:
  name: sysz-config
  namespace: sysz
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sysz-sidecar-config
  namespace: sysz
data:
  docker-env: "true"
  in-cluster: "true"
  sidecar-port: "49449"
