apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sysz
  namespace: pf-testing
  labels:
    app: sysz-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sysz-app
  template:
    metadata:
      labels:
        app: sysz-app
    spec:
      containers:
        - name: sysz
          image: acrQat.azurecr.io/sysz:v0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8284
          env:
            - name: IN_CLUSTER
              valueFrom:
                  configMapKeyRef:
                    name: sysz-config
                    key: in-cluster
            - name: DOCKER_ENV
              valueFrom:
                configMapKeyRef:
                  name: sysz-config
                  key: docker-env
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8284
              httpHeaders:
                - name: X-Liveness-Probe-Test
                  value: "true"
            initialDelaySeconds: 5
            periodSeconds: 30
          volumeMounts:
            - name: logvolume
              mountPath: /var/log
        # Sidecar Container
        - name: log-sidecar
          image: acrQat.azurecr.io/sysz-logsidecar:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 49449
          env:
            - name: DOCKER_ENV
              valueFrom:
                  configMapKeyRef:
                    name: sysz-sidecar-config
                    key: docker-env
            - name: SIDECAR_PORT
              valueFrom:
                configMapKeyRef:
                  name: sysz-sidecar-config
                  key: sidecar-port
          volumeMounts:
            - name: logvolume
              mountPath: /var/log
      volumes:
      - name: logvolume
        emptyDir: {}
      imagePullSecrets:
        - name: secqat
