apiVersion: v1
kind: Service
metadata:
  name: sysz-service
  namespace: sysz
  labels:
    expose: "true"
spec:
  selector:
    app: sysz-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8284
  type: LoadBalancer