apiVersion: v1
kind: Service
metadata:
  name: sysz-service
  namespace: sysz
  labels:
    expose: "true"
spec:
  selector:
    app: sysz-app
  ports:
    - protocol: TCP
      port: 80
      name: "sysz"
      targetPort: 8284
    - protocol: TCP
      name: "log-sidecar"
      port: 49449
      targetPort: 49449
  type: LoadBalancer