// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_7e70e7c58bfcf72f, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type InfoResponse struct {
	Port                 string      `protobuf:"bytes,1,opt,name=Port,proto3" json:"Port,omitempty"`
	ServerID             string      `protobuf:"bytes,2,opt,name=ServerID,proto3" json:"ServerID,omitempty"`
	K8SSession           *K8SSession `protobuf:"bytes,4,opt,name=K8sSession,proto3" json:"K8sSession,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *InfoResponse) Reset()         { *m = InfoResponse{} }
func (m *InfoResponse) String() string { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()    {}
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_7e70e7c58bfcf72f, []int{1}
}
func (m *InfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoResponse.Unmarshal(m, b)
}
func (m *InfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoResponse.Marshal(b, m, deterministic)
}
func (dst *InfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoResponse.Merge(dst, src)
}
func (m *InfoResponse) XXX_Size() int {
	return xxx_messageInfo_InfoResponse.Size(m)
}
func (m *InfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InfoResponse proto.InternalMessageInfo

func (m *InfoResponse) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *InfoResponse) GetServerID() string {
	if m != nil {
		return m.ServerID
	}
	return ""
}

func (m *InfoResponse) GetK8SSession() *K8SSession {
	if m != nil {
		return m.K8SSession
	}
	return nil
}

type K8SSession struct {
	ServerAddress        string   `protobuf:"bytes,1,opt,name=ServerAddress,proto3" json:"ServerAddress,omitempty"`
	ServerPort           uint32   `protobuf:"varint,2,opt,name=ServerPort,proto3" json:"ServerPort,omitempty"`
	ServerBaseUrl        string   `protobuf:"bytes,3,opt,name=ServerBaseUrl,proto3" json:"ServerBaseUrl,omitempty"`
	AccessToken          string   `protobuf:"bytes,4,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
	ApiCalls             uint64   `protobuf:"varint,5,opt,name=ApiCalls,proto3" json:"ApiCalls,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *K8SSession) Reset()         { *m = K8SSession{} }
func (m *K8SSession) String() string { return proto.CompactTextString(m) }
func (*K8SSession) ProtoMessage()    {}
func (*K8SSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_7e70e7c58bfcf72f, []int{2}
}
func (m *K8SSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_K8SSession.Unmarshal(m, b)
}
func (m *K8SSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_K8SSession.Marshal(b, m, deterministic)
}
func (dst *K8SSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_K8SSession.Merge(dst, src)
}
func (m *K8SSession) XXX_Size() int {
	return xxx_messageInfo_K8SSession.Size(m)
}
func (m *K8SSession) XXX_DiscardUnknown() {
	xxx_messageInfo_K8SSession.DiscardUnknown(m)
}

var xxx_messageInfo_K8SSession proto.InternalMessageInfo

func (m *K8SSession) GetServerAddress() string {
	if m != nil {
		return m.ServerAddress
	}
	return ""
}

func (m *K8SSession) GetServerPort() uint32 {
	if m != nil {
		return m.ServerPort
	}
	return 0
}

func (m *K8SSession) GetServerBaseUrl() string {
	if m != nil {
		return m.ServerBaseUrl
	}
	return ""
}

func (m *K8SSession) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *K8SSession) GetApiCalls() uint64 {
	if m != nil {
		return m.ApiCalls
	}
	return 0
}

type JobRequest struct {
	// This will always be transported in base64 to the server
	// First step will always decode from base64
	JobDescInYaml        string   `protobuf:"bytes,1,opt,name=JobDescInYaml,proto3" json:"JobDescInYaml,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobRequest) Reset()         { *m = JobRequest{} }
func (m *JobRequest) String() string { return proto.CompactTextString(m) }
func (*JobRequest) ProtoMessage()    {}
func (*JobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_7e70e7c58bfcf72f, []int{3}
}
func (m *JobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobRequest.Unmarshal(m, b)
}
func (m *JobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobRequest.Marshal(b, m, deterministic)
}
func (dst *JobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobRequest.Merge(dst, src)
}
func (m *JobRequest) XXX_Size() int {
	return xxx_messageInfo_JobRequest.Size(m)
}
func (m *JobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobRequest proto.InternalMessageInfo

func (m *JobRequest) GetJobDescInYaml() string {
	if m != nil {
		return m.JobDescInYaml
	}
	return ""
}

func (m *JobRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type JobResponse struct {
	JobID                string   `protobuf:"bytes,1,opt,name=JobID,proto3" json:"JobID,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	CreatedAt            int64    `protobuf:"varint,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobResponse) Reset()         { *m = JobResponse{} }
func (m *JobResponse) String() string { return proto.CompactTextString(m) }
func (*JobResponse) ProtoMessage()    {}
func (*JobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_7e70e7c58bfcf72f, []int{4}
}
func (m *JobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobResponse.Unmarshal(m, b)
}
func (m *JobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobResponse.Marshal(b, m, deterministic)
}
func (dst *JobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobResponse.Merge(dst, src)
}
func (m *JobResponse) XXX_Size() int {
	return xxx_messageInfo_JobResponse.Size(m)
}
func (m *JobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobResponse proto.InternalMessageInfo

func (m *JobResponse) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

func (m *JobResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *JobResponse) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*InfoResponse)(nil), "InfoResponse")
	proto.RegisterType((*K8SSession)(nil), "K8sSession")
	proto.RegisterType((*JobRequest)(nil), "JobRequest")
	proto.RegisterType((*JobResponse)(nil), "JobResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ZuesControlClient is the client API for ZuesControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ZuesControlClient interface {
	GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InfoResponse, error)
	DeployJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobResponse, error)
}

type zuesControlClient struct {
	cc *grpc.ClientConn
}

func NewZuesControlClient(cc *grpc.ClientConn) ZuesControlClient {
	return &zuesControlClient{cc}
}

func (c *zuesControlClient) GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, "/ZuesControl/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zuesControlClient) DeployJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, "/ZuesControl/DeployJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZuesControlServer is the server API for ZuesControl service.
type ZuesControlServer interface {
	GetInfo(context.Context, *Empty) (*InfoResponse, error)
	DeployJob(context.Context, *JobRequest) (*JobResponse, error)
}

func RegisterZuesControlServer(s *grpc.Server, srv ZuesControlServer) {
	s.RegisterService(&_ZuesControl_serviceDesc, srv)
}

func _ZuesControl_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZuesControlServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ZuesControl/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZuesControlServer).GetInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZuesControl_DeployJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZuesControlServer).DeployJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ZuesControl/DeployJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZuesControlServer).DeployJob(ctx, req.(*JobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ZuesControl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ZuesControl",
	HandlerType: (*ZuesControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _ZuesControl_GetInfo_Handler,
		},
		{
			MethodName: "DeployJob",
			Handler:    _ZuesControl_DeployJob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_server_7e70e7c58bfcf72f) }

var fileDescriptor_server_7e70e7c58bfcf72f = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0x4f, 0x6f, 0x9b, 0x40,
	0x10, 0xc5, 0x4d, 0xfd, 0xaf, 0x0c, 0xf6, 0x65, 0x55, 0x55, 0xc8, 0xaa, 0x2a, 0xb4, 0xea, 0x01,
	0xa9, 0x12, 0x07, 0xf7, 0xd2, 0x2b, 0x31, 0x51, 0x04, 0xb9, 0x58, 0x6b, 0xe7, 0xe0, 0xe4, 0x04,
	0xf6, 0x44, 0xb2, 0x0c, 0x2c, 0xd9, 0x59, 0x47, 0xf2, 0x17, 0xcb, 0xe7, 0x8b, 0x58, 0x88, 0xc1,
	0x37, 0xde, 0x8f, 0xdd, 0x37, 0x6f, 0x66, 0x16, 0x66, 0x84, 0xea, 0x1d, 0x55, 0x50, 0x29, 0xa9,
	0x25, 0x9f, 0xc2, 0xf8, 0xbe, 0xa8, 0xf4, 0x85, 0x9f, 0x60, 0x16, 0x97, 0xaf, 0x52, 0x20, 0x55,
	0xb2, 0x24, 0x64, 0x0c, 0x46, 0x6b, 0xa9, 0xb4, 0x6b, 0x79, 0x96, 0x6f, 0x0b, 0xf3, 0xcd, 0x16,
	0xf0, 0x7d, 0x63, 0x2e, 0xc7, 0x91, 0xfb, 0xcd, 0xf0, 0xab, 0x66, 0x7f, 0x01, 0x1e, 0xff, 0xd3,
	0x06, 0x89, 0x8e, 0xb2, 0x74, 0x47, 0x9e, 0xe5, 0x3b, 0x4b, 0x27, 0xe8, 0x90, 0xe8, 0xfd, 0xe6,
	0x1f, 0x56, 0xff, 0x34, 0xfb, 0x03, 0xf3, 0xc6, 0x27, 0x3c, 0x1c, 0x14, 0x12, 0xb5, 0x45, 0x6f,
	0x21, 0xfb, 0x0d, 0xd0, 0x00, 0x93, 0xab, 0xae, 0x3f, 0x17, 0x3d, 0xd2, 0xb9, 0xdc, 0xa5, 0x84,
	0x4f, 0x2a, 0x77, 0x87, 0x7d, 0x97, 0x16, 0x32, 0x0f, 0x9c, 0x70, 0xbf, 0x47, 0xa2, 0xad, 0x3c,
	0x61, 0x13, 0xd4, 0x16, 0x7d, 0x54, 0x77, 0x19, 0x56, 0xc7, 0x55, 0x9a, 0xe7, 0xe4, 0x8e, 0x3d,
	0xcb, 0x1f, 0x89, 0xab, 0xe6, 0x6b, 0x80, 0x44, 0x66, 0x02, 0xdf, 0xce, 0x48, 0xa6, 0x62, 0x22,
	0xb3, 0x08, 0x69, 0x1f, 0x97, 0xbb, 0xb4, 0xc8, 0xbf, 0x72, 0xdf, 0x40, 0xf6, 0x0b, 0xec, 0xed,
	0xb1, 0x40, 0xd2, 0x69, 0x51, 0x99, 0xd8, 0x43, 0xd1, 0x01, 0xbe, 0x03, 0xc7, 0x38, 0xb6, 0x63,
	0xff, 0x01, 0xe3, 0x44, 0x66, 0x71, 0xd4, 0x5a, 0x35, 0x82, 0xfd, 0x84, 0xc9, 0x46, 0xa7, 0xfa,
	0x4c, 0xed, 0xd8, 0x5b, 0x55, 0x5b, 0xaf, 0x14, 0xa6, 0x1a, 0x0f, 0xa1, 0x36, 0xed, 0x0e, 0x45,
	0x07, 0x96, 0x2f, 0xe0, 0x3c, 0x9f, 0x91, 0x56, 0xb2, 0xd4, 0x4a, 0xe6, 0x8c, 0xc3, 0xf4, 0x01,
	0x75, 0xbd, 0x64, 0x36, 0x09, 0xcc, 0xd2, 0x17, 0xf3, 0xa0, 0xbf, 0x73, 0x3e, 0x60, 0x3e, 0xd8,
	0x11, 0x56, 0xb9, 0xbc, 0x24, 0x32, 0x63, 0x4e, 0xd0, 0xf5, 0xba, 0x98, 0x05, 0xbd, 0x98, 0x7c,
	0x90, 0x4d, 0xcc, 0xfb, 0xf9, 0xf7, 0x19, 0x00, 0x00, 0xff, 0xff, 0xd6, 0xaf, 0x4e, 0x7e, 0x4f,
	0x02, 0x00, 0x00,
}
