// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_7c8bbf4131488981, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type InfoResponse struct {
	Port                 string   `protobuf:"bytes,1,opt,name=Port,proto3" json:"Port,omitempty"`
	ServerID             string   `protobuf:"bytes,2,opt,name=ServerID,proto3" json:"ServerID,omitempty"`
	Health               string   `protobuf:"bytes,3,opt,name=health,proto3" json:"health,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoResponse) Reset()         { *m = InfoResponse{} }
func (m *InfoResponse) String() string { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()    {}
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_7c8bbf4131488981, []int{1}
}
func (m *InfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoResponse.Unmarshal(m, b)
}
func (m *InfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoResponse.Marshal(b, m, deterministic)
}
func (dst *InfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoResponse.Merge(dst, src)
}
func (m *InfoResponse) XXX_Size() int {
	return xxx_messageInfo_InfoResponse.Size(m)
}
func (m *InfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InfoResponse proto.InternalMessageInfo

func (m *InfoResponse) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *InfoResponse) GetServerID() string {
	if m != nil {
		return m.ServerID
	}
	return ""
}

func (m *InfoResponse) GetHealth() string {
	if m != nil {
		return m.Health
	}
	return ""
}

type JobRequest struct {
	// This will always be transported in base64 to the server
	// First step will always decode from base64
	JobDescInYaml        string   `protobuf:"bytes,1,opt,name=JobDescInYaml,proto3" json:"JobDescInYaml,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	JobID                string   `protobuf:"bytes,3,opt,name=JobID,proto3" json:"JobID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobRequest) Reset()         { *m = JobRequest{} }
func (m *JobRequest) String() string { return proto.CompactTextString(m) }
func (*JobRequest) ProtoMessage()    {}
func (*JobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_7c8bbf4131488981, []int{2}
}
func (m *JobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobRequest.Unmarshal(m, b)
}
func (m *JobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobRequest.Marshal(b, m, deterministic)
}
func (dst *JobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobRequest.Merge(dst, src)
}
func (m *JobRequest) XXX_Size() int {
	return xxx_messageInfo_JobRequest.Size(m)
}
func (m *JobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JobRequest proto.InternalMessageInfo

func (m *JobRequest) GetJobDescInYaml() string {
	if m != nil {
		return m.JobDescInYaml
	}
	return ""
}

func (m *JobRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *JobRequest) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

type JobResponse struct {
	JobID                string   `protobuf:"bytes,1,opt,name=JobID,proto3" json:"JobID,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=Status,proto3" json:"Status,omitempty"`
	CreatedAt            int64    `protobuf:"varint,3,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobResponse) Reset()         { *m = JobResponse{} }
func (m *JobResponse) String() string { return proto.CompactTextString(m) }
func (*JobResponse) ProtoMessage()    {}
func (*JobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_7c8bbf4131488981, []int{3}
}
func (m *JobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobResponse.Unmarshal(m, b)
}
func (m *JobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobResponse.Marshal(b, m, deterministic)
}
func (dst *JobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobResponse.Merge(dst, src)
}
func (m *JobResponse) XXX_Size() int {
	return xxx_messageInfo_JobResponse.Size(m)
}
func (m *JobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobResponse proto.InternalMessageInfo

func (m *JobResponse) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

func (m *JobResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *JobResponse) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type JobDetailResponse struct {
	JobID                string   `protobuf:"bytes,1,opt,name=JobID,proto3" json:"JobID,omitempty"`
	JobStatus            string   `protobuf:"bytes,2,opt,name=JobStatus,proto3" json:"JobStatus,omitempty"`
	MaxBuildErrors       int32    `protobuf:"varint,3,opt,name=MaxBuildErrors,proto3" json:"MaxBuildErrors,omitempty"`
	MaxRetries           int32    `protobuf:"varint,4,opt,name=MaxRetries,proto3" json:"MaxRetries,omitempty"`
	ErrorsOccured        int32    `protobuf:"varint,5,opt,name=ErrorsOccured,proto3" json:"ErrorsOccured,omitempty"`
	RetriesOccured       int32    `protobuf:"varint,6,opt,name=RetriesOccured,proto3" json:"RetriesOccured,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JobDetailResponse) Reset()         { *m = JobDetailResponse{} }
func (m *JobDetailResponse) String() string { return proto.CompactTextString(m) }
func (*JobDetailResponse) ProtoMessage()    {}
func (*JobDetailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_7c8bbf4131488981, []int{4}
}
func (m *JobDetailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobDetailResponse.Unmarshal(m, b)
}
func (m *JobDetailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobDetailResponse.Marshal(b, m, deterministic)
}
func (dst *JobDetailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobDetailResponse.Merge(dst, src)
}
func (m *JobDetailResponse) XXX_Size() int {
	return xxx_messageInfo_JobDetailResponse.Size(m)
}
func (m *JobDetailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JobDetailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JobDetailResponse proto.InternalMessageInfo

func (m *JobDetailResponse) GetJobID() string {
	if m != nil {
		return m.JobID
	}
	return ""
}

func (m *JobDetailResponse) GetJobStatus() string {
	if m != nil {
		return m.JobStatus
	}
	return ""
}

func (m *JobDetailResponse) GetMaxBuildErrors() int32 {
	if m != nil {
		return m.MaxBuildErrors
	}
	return 0
}

func (m *JobDetailResponse) GetMaxRetries() int32 {
	if m != nil {
		return m.MaxRetries
	}
	return 0
}

func (m *JobDetailResponse) GetErrorsOccured() int32 {
	if m != nil {
		return m.ErrorsOccured
	}
	return 0
}

func (m *JobDetailResponse) GetRetriesOccured() int32 {
	if m != nil {
		return m.RetriesOccured
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*InfoResponse)(nil), "InfoResponse")
	proto.RegisterType((*JobRequest)(nil), "JobRequest")
	proto.RegisterType((*JobResponse)(nil), "JobResponse")
	proto.RegisterType((*JobDetailResponse)(nil), "JobDetailResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ZuesControlClient is the client API for ZuesControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ZuesControlClient interface {
	GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InfoResponse, error)
	DeployJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobResponse, error)
	JobDetails(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobDetailResponse, error)
}

type zuesControlClient struct {
	cc *grpc.ClientConn
}

func NewZuesControlClient(cc *grpc.ClientConn) ZuesControlClient {
	return &zuesControlClient{cc}
}

func (c *zuesControlClient) GetInfo(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, "/ZuesControl/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zuesControlClient) DeployJob(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobResponse, error) {
	out := new(JobResponse)
	err := c.cc.Invoke(ctx, "/ZuesControl/DeployJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *zuesControlClient) JobDetails(ctx context.Context, in *JobRequest, opts ...grpc.CallOption) (*JobDetailResponse, error) {
	out := new(JobDetailResponse)
	err := c.cc.Invoke(ctx, "/ZuesControl/JobDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZuesControlServer is the server API for ZuesControl service.
type ZuesControlServer interface {
	GetInfo(context.Context, *Empty) (*InfoResponse, error)
	DeployJob(context.Context, *JobRequest) (*JobResponse, error)
	JobDetails(context.Context, *JobRequest) (*JobDetailResponse, error)
}

func RegisterZuesControlServer(s *grpc.Server, srv ZuesControlServer) {
	s.RegisterService(&_ZuesControl_serviceDesc, srv)
}

func _ZuesControl_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZuesControlServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ZuesControl/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZuesControlServer).GetInfo(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZuesControl_DeployJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZuesControlServer).DeployJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ZuesControl/DeployJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZuesControlServer).DeployJob(ctx, req.(*JobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ZuesControl_JobDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZuesControlServer).JobDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ZuesControl/JobDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZuesControlServer).JobDetails(ctx, req.(*JobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ZuesControl_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ZuesControl",
	HandlerType: (*ZuesControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _ZuesControl_GetInfo_Handler,
		},
		{
			MethodName: "DeployJob",
			Handler:    _ZuesControl_DeployJob_Handler,
		},
		{
			MethodName: "JobDetails",
			Handler:    _ZuesControl_JobDetails_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_server_7c8bbf4131488981) }

var fileDescriptor_server_7c8bbf4131488981 = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xd1, 0x6a, 0xa3, 0x40,
	0x14, 0x86, 0xe3, 0x26, 0x9a, 0xf5, 0x24, 0x59, 0xd8, 0x61, 0x59, 0x24, 0x84, 0x65, 0x19, 0x96,
	0x25, 0x57, 0x2e, 0x6c, 0x9f, 0xa0, 0x8d, 0xa1, 0x28, 0x84, 0x16, 0x53, 0x0a, 0xe9, 0xdd, 0x98,
	0x9c, 0x10, 0x41, 0x1d, 0x3b, 0x33, 0x96, 0xe4, 0x1d, 0xfa, 0x8a, 0x7d, 0x97, 0xe2, 0x68, 0xa3,
	0xb6, 0x17, 0xbd, 0xf3, 0x7c, 0xfe, 0x33, 0xdf, 0xe1, 0xcc, 0x81, 0xb1, 0x44, 0xf1, 0x84, 0xc2,
	0xcd, 0x05, 0x57, 0x9c, 0x0e, 0xc1, 0x5c, 0xa6, 0xb9, 0x3a, 0xd1, 0x7b, 0x18, 0xfb, 0xd9, 0x9e,
	0x87, 0x28, 0x73, 0x9e, 0x49, 0x24, 0x04, 0x06, 0xb7, 0x5c, 0x28, 0xc7, 0xf8, 0x6d, 0xcc, 0xed,
	0x50, 0x7f, 0x93, 0x29, 0x7c, 0x5d, 0xeb, 0xc3, 0xbe, 0xe7, 0x7c, 0xd1, 0xfc, 0x5c, 0x93, 0x9f,
	0x60, 0x1d, 0x90, 0x25, 0xea, 0xe0, 0xf4, 0xf5, 0x9f, 0xba, 0xa2, 0x7b, 0x80, 0x80, 0x47, 0x21,
	0x3e, 0x16, 0x28, 0x15, 0xf9, 0x03, 0x93, 0x80, 0x47, 0x1e, 0xca, 0xad, 0x9f, 0x6d, 0x58, 0x9a,
	0xd4, 0xd7, 0x77, 0x21, 0x99, 0x81, 0x7d, 0x17, 0xa7, 0x28, 0x15, 0x4b, 0x73, 0x2d, 0xea, 0x87,
	0x0d, 0x20, 0x3f, 0xc0, 0x0c, 0x78, 0xe4, 0x7b, 0xb5, 0xa8, 0x2a, 0xe8, 0x06, 0x46, 0xda, 0x53,
	0xb7, 0x7f, 0x0e, 0x19, 0xad, 0x50, 0xd9, 0xe4, 0x5a, 0x31, 0x55, 0xc8, 0xba, 0xfd, 0xba, 0x2a,
	0x85, 0x0b, 0x81, 0x4c, 0xe1, 0xee, 0x52, 0xe9, 0x6b, 0xfb, 0x61, 0x03, 0xe8, 0x8b, 0x01, 0xdf,
	0x75, 0x83, 0x8a, 0xc5, 0xc9, 0x27, 0x86, 0x19, 0xd8, 0x01, 0x8f, 0x3a, 0x92, 0x06, 0x90, 0xbf,
	0xf0, 0x6d, 0xc5, 0x8e, 0x57, 0x45, 0x9c, 0xec, 0x96, 0x42, 0x70, 0x21, 0xb5, 0xcc, 0x0c, 0xdf,
	0x51, 0xf2, 0x0b, 0x60, 0xc5, 0x8e, 0x21, 0x2a, 0x11, 0xa3, 0x74, 0x06, 0x3a, 0xd3, 0x22, 0xe5,
	0x18, 0xab, 0xe4, 0xcd, 0x76, 0x5b, 0x08, 0xdc, 0x39, 0xa6, 0x8e, 0x74, 0x61, 0x69, 0xab, 0x0f,
	0xbc, 0xc5, 0xac, 0xca, 0xd6, 0xa5, 0xff, 0x9f, 0x0d, 0x18, 0x3d, 0x14, 0x28, 0x17, 0x3c, 0x53,
	0x82, 0x27, 0x84, 0xc2, 0xf0, 0x1a, 0x55, 0xb9, 0x0d, 0xc4, 0x72, 0xf5, 0x76, 0x4c, 0x27, 0x6e,
	0x7b, 0x39, 0x68, 0x8f, 0xcc, 0xc1, 0xf6, 0x30, 0x4f, 0xf8, 0x29, 0xe0, 0x11, 0x19, 0xb9, 0xcd,
	0x13, 0x4f, 0xc7, 0x6e, 0xeb, 0x1d, 0x68, 0x8f, 0xfc, 0xd3, 0x0b, 0x50, 0x0d, 0x4f, 0x76, 0xa3,
	0xc4, 0xfd, 0x30, 0x56, 0xda, 0x8b, 0x2c, 0xbd, 0x99, 0x17, 0xaf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xec, 0x0f, 0x44, 0x75, 0xa9, 0x02, 0x00, 0x00,
}
